@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Employee",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1258113742 { 
   	label=Employee
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Employee1258113742[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Employee</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   birthYear: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   clockInTime: LocalTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   clockOutTime: LocalTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   hoursWorked: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   position: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rate: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sex: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ age(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ calculateHoursWorkedPerDay()</TD></TR>
<TR><TD ALIGN="LEFT" >+ calculateSalary(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ clockIn(): LocalTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ clockOut(): LocalTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ resetMonthlyValues()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_294598911 { 
   	label=EmployeeManager
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   EmployeeManager294598911[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EmployeeManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   employees: LinkedList&lt;Employee&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addEmployee(employee: Employee)</TD></TR>
<TR><TD ALIGN="LEFT" >+ calculateTotalSalary(): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ displayAllEmployees()</TD></TR>
<TR><TD ALIGN="LEFT" >+ displayEmployeesByPosition(position: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- findEmployeeById(employeeId: int): Employee</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeEmployee(employeeId: int)</TD></TR>
<TR><TD ALIGN="LEFT" >- resetMonthlyValuesForAllEmployees()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
EmployeeManager294598911 -> Employee1258113742[label="employees
[0..*]"];
    
}
@enduml